
/**
 * ============================================================
 * Banco de Preguntas — ContiChallenge v3.6.0
 * 132 preguntas para "ContiChallenge: Desafío Contable y Financiero"
 * ============================================================
 * Estructura:
 *   - generalQuestions: 25 preguntas (conceptos básicos)
 *   - fondoEmergenciaQuestions: 32 preguntas
 *     Grupo A (primeras 17): 5 aleatorias para posiciones 1-5
 *     Grupo B (últimas 15): 5 aleatorias para posiciones 6-10
 *   - nivel2Questions: 25 preguntas (Contabilidad y Nómina)
 *   - nivel3Questions: 25 preguntas (Estados Financieros)
 *   - nivelAvanzadoQuestions: 25 preguntas (Cálculos Avanzados)
 */

// ------------------------------------------------------------
// BANCO GENERAL / CONCEPTOS BÁSICOS (25 Preguntas)
// ------------------------------------------------------------
const generalQuestions = [
    {
        id: 1, topic: 'presupuesto', type: 'multiple',
        question: '¿Qué es un presupuesto personal o familiar?',
        options: ['Un plan financiero que proyecta ingresos y gastos', 'Un tipo de impuesto cobrado por el SII', 'El saldo final de una cuenta corriente', 'Un crédito solicitado al banco'],
        correct: 0,
        explanation: 'Un presupuesto proyecta tus ingresos y prevé los gastos en un período determinado para mantener la estabilidad financiera.',
        hint: 'Es una herramienta de planificación previa al uso del dinero.',
        points: 100
    },
    {
        id: 2, topic: 'contabilidad', type: 'multiple',
        question: '¿Cuál es el objetivo principal de la contabilidad en una empresa?',
        options: ['Registrar, clasificar y resumir operaciones financieras para la toma de decisiones', 'Calcular únicamente las vacaciones del personal', 'Diseñar campañas publicitarias y de ventas', 'Fijar libremente los precios de mercado'],
        correct: 0,
        explanation: 'La contabilidad proporciona información estructurada y fidedigna sobre la situación financiera de la entidad.',
        hint: 'Abarca el ciclo completo de la información económica y financiera.',
        points: 100
    },
    {
        id: 3, topic: 'inversion', type: 'multiple',
        question: '¿En qué consiste la diversificación de inversiones?',
        options: ['Distribuir los recursos en diferentes activos para minimizar riesgos', 'Invertir todo el capital en un solo fondo mutuo', 'Mantener todo el dinero en efectivo bajo el colchón', 'Gastar las ganancias en bienes de consumo inmediato'],
        correct: 0,
        explanation: 'Diversificar reduce el impacto negativo si uno de los activos disminuye su rendimiento.',
        hint: 'Busca mitigar pérdidas repartiendo el capital en distintas alternativas.',
        points: 100
    },
    {
        id: 4, topic: 'credito', type: 'multiple',
        question: '¿Qué mide el informe comercial e historial crediticio (ej. Dicom) en Chile?',
        options: ['El comportamiento histórico de pago y cumplimiento de deudas', 'La cantidad de dinero ahorrada en la AFP', 'El nivel de educación formal alcanzado', 'El saldo disponible en la tarjeta de débito'],
        correct: 0,
        explanation: 'El historial crediticio evalúa el riesgo financiero de una persona según su puntualidad en el pago de compromisos.',
        hint: 'Es la carta de presentación financiera ante los evaluadores de crédito.',
        points: 100
    },
    {
        id: 5, topic: 'contabilidad', type: 'multiple',
        question: 'En la estructura contable, ¿qué define a un "Activo"?',
        options: ['Recursos y bienes controlados por la empresa con potencial de generar beneficios', 'Las obligaciones y deudas pendientes con proveedores', 'El capital aportado únicamente por los accionistas', 'Los gastos operacionales del período'],
        correct: 0,
        explanation: 'Los Activos son los bienes, derechos y recursos económicos que posee una entidad.',
        hint: 'Incluye caja, bancos, mercaderías, maquinarias y cuentas por cobrar.',
        points: 100
    },
    {
        id: 6, topic: 'presupuesto', type: 'matching',
        question: 'Empareja cada concepto financiero con su definición:',
        pairs: [
            { left: 'Ingreso', right: 'Flujo de dinero percibido', id: 1 },
            { left: 'Gasto', right: 'Desembolso por bienes/servicios', id: 2 },
            { left: 'Ahorro', right: 'Excedente no consumido del ingreso', id: 3 },
            { left: 'Inversión', right: 'Capital destinado a generar rentabilidad', id: 4 }
        ],
        hint: 'Relaciona entradas, salidas, reservas y capital productivo.',
        points: 200
    },
    {
        id: 7, topic: 'credito', type: 'multiple',
        question: '¿Qué representa la Carga Anual Equivalente (CAE) en un crédito de consumo?',
        options: ['El costo total del crédito expresado en un porcentaje anual', 'El pago mínimo mensual sugerido', 'El monto tope de endeudamiento permitido', 'El impuesto de timbres y estampillas'],
        correct: 0,
        explanation: 'La CAE integra la tasa de interés, comisiones, seguros y todos los gastos asociados al crédito en un solo indicador comparable.',
        hint: 'Permite comparar objetivamente qué institución financiera es más barata.',
        points: 150
    },
    {
        id: 8, topic: 'contabilidad', type: 'multiple',
        question: '¿Cuál es la Ecuación Fundamental de la Contabilidad?',
        options: ['Activo = Pasivo + Patrimonio', 'Activo = Ingresos - Gastos', 'Pasivo = Activo + Patrimonio', 'Patrimonio = Pasivo - Activo'],
        correct: 0,
        explanation: 'Todo lo que la empresa posee (Activo) ha sido financiado por terceros (Pasivo) o por los dueños (Patrimonio).',
        hint: 'Mantiene el equilibrio permanente de la doble entrada.',
        points: 100
    },
    {
        id: 9, topic: 'finanzas', type: 'drag',
        question: 'Ordena las etapas para elaborar una planificación financiera eficiente:',
        items: ['Diagnosticar ingresos y gastos actuales', 'Definir objetivos financieros', 'Construir el presupuesto mensual', 'Ejecutar el plan de ahorro e inversión', 'Evaluar y reajustar periódicamente'],
        hint: 'Inicia con el diagnóstico de situación actual y termina con la revisión.',
        points: 200
    },
    {
        id: 10, topic: 'presupuesto', type: 'multiple',
        question: '¿A qué se refiere el concepto de "gasto hormiga"?',
        options: ['Sumas pequeñas de consumo diario no planificado que afectan el presupuesto', 'Afectaciones por plagas en inventarios', 'Compras al por mayor con descuentos', 'Gastos de mantención industrial'],
        correct: 0,
        explanation: 'Son compras menores pero repetitivas que acumuladas representan un monto elevado.',
        hint: 'Parecen inofensivos de forma aislada, pero impactan el total acumulado.',
        points: 100
    },
    {
        id: 11, topic: 'credito', type: 'multiple',
        question: '¿Qué es el costo total del crédito (CTC)?',
        options: ['La suma de todas las cuotas a pagar más gastos asociados', 'El monto neto prestado inicialmente', 'La comisión por abrir una cuenta de ahorro', 'El valor de la UF al momento de solicitarlo'],
        correct: 0,
        explanation: 'El CTC es el monto final real que desembolsará el cliente al término de todas las cuotas.',
        hint: 'Incluye capital, intereses, seguros y comisiones finales.',
        points: 100
    },
    {
        id: 12, topic: 'finanzas', type: 'multiple',
        question: '¿Qué organismo público regula y fiscaliza el mercado de valores y seguros en Chile?',
        options: ['Comisión para el Mercado Financiero (CMF)', 'Servicio de Impuestos Internos (SII)', 'Tesorería General de la República', 'Subsecretaría de Economía'],
        correct: 0,
        explanation: 'La CMF vela por la transparencia y estabilidad del sistema financiero en Chile.',
        hint: 'Fiscaliza a bancos, aseguradoras y administradoras de fondos.',
        points: 100
    },
    {
        id: 13, topic: 'presupuesto', type: 'multiple',
        question: '¿Qué es la regla presupuestaria 50/30/20?',
        options: ['50% necesidades, 30% deseos, 20% ahorro e inversión', '50% ahorro, 30% gastos fijos, 20% impuestos', '50% deudas, 30% comida, 20% arriendo', '50% inversión, 30% ocio, 20% fondo de riesgo'],
        correct: 0,
        explanation: 'Es una metodología popular de educación financiera para distribuir de forma razonable los ingresos netos.',
        hint: 'Destina la mitad a lo vital, un tercio a gustos y la quinta parte al futuro.',
        points: 100
    },
    {
        id: 14, topic: 'credito', type: 'multiple',
        question: '¿Cuál es la función del interés moratorio?',
        options: ['Sancionar o cobrar un recargo por el retraso en el pago de una cuota', 'Premiar el pago anticipado de una deuda', 'Descontar impuestos en compras con tarjeta', 'Reducir la tasa de interés base'],
        correct: 0,
        explanation: 'El interés moratorio aplica únicamente cuando el deudor incurre en mora o atraso fuera del plazo pactado.',
        hint: 'Aplica solo ante el incumplimiento de la fecha de vencimiento.',
        points: 100
    },
    {
        id: 15, topic: 'contabilidad', type: 'multiple',
        question: 'En términos contables, ¿qué representa un "Pasivo"?',
        options: ['Deudas y obligaciones financieras pendientes de pago', 'Los recursos acumulados en la caja chica', 'El capital aportado por los dueños', 'Las utilidades acumuladas del año anterior'],
        correct: 0,
        explanation: 'Los pasivos reflejan las obligaciones financieras frente a terceros (proveedores, bancos, empleados).',
        hint: 'Es todo lo que la empresa debe a fuentes externas.',
        points: 100
    },
    {
        id: 16, topic: 'inversion', type: 'multiple',
        question: '¿Qué es la rentabilidad en una inversión?',
        options: ['La ganancia o pérdida generada sobre el capital invertido', 'El valor máximo fijado para cobrar impuestos', 'El cobro mensual por mantención de cuenta', 'El monto mínimo requerido para abrir un negocio'],
        correct: 0,
        explanation: 'Mide la variación del valor del capital inicial expresado en un porcentaje o monto.',
        hint: 'Indica qué tan productivo ha sido el capital empleado.',
        points: 100
    },
    {
        id: 17, topic: 'finanzas', type: 'multiple',
        question: '¿Qué es la inflación?',
        options: ['El aumento generalizado y sostenido de los precios de bienes y servicios', 'El descuento aplicado durante eventos como el CyberDay', 'El incremento constante del sueldo mínimo', 'La devaluación del dólar respecto al euro'],
        correct: 0,
        explanation: 'La inflación reduce el poder adquisitivo de la moneda a lo largo del tiempo.',
        hint: 'Hace que con la misma cantidad de dinero compres menos cosas.',
        points: 100
    },
    {
        id: 18, topic: 'finanzas', type: 'multiple',
        question: 'En Chile, ¿qué indicador se utiliza comunmente para reajustar valores según la inflación?',
        options: ['Unidad de Fomento (UF)', 'Índice de Precios al Consumidor (IPC)', 'Tasa de Política Monetaria (TPM)', 'Dólar Observado'],
        correct: 0,
        explanation: 'La UF es una unidad de cuenta reajustable según la variación del IPC diario.',
        hint: 'Se usa habitualmente en dividendos, arriendos y créditos hipotecarios.',
        points: 100
    },
    {
        id: 19, topic: 'presupuesto', type: 'multiple',
        question: '¿Qué es un gasto fijo en un presupuesto personal?',
        options: ['Un desembolso cuyo monto y frecuencia son recurrentes y predecibles', 'Una compra de imprevisto por emergencia médica', 'Un gasto variable dependiente del entretenimiento', 'Una inversión realizada en fondos mutuos'],
        correct: 0,
        explanation: 'Los gastos fijos (como arriendo o escolaridad) son indispensables y previsibles mes a mes.',
        hint: 'No cambian drásticamente de un mes a otro y deben pagarse sí o sí.',
        points: 100
    },
    {
        id: 20, topic: 'contabilidad', type: 'multiple',
        question: '¿Qué es el "Patrimonio" de una empresa?',
        options: ['El valor residual de los activos de la entidad una vez deducidos todos sus pasivos', 'El total acumulado en efectivo en los bancos', 'El valor bruto de las ventas del mes', 'Los impuestos pendientes de devolución'],
        correct: 0,
        explanation: 'El Patrimonio Neto representa la participación o aporte neto de los propietarios en la empresa.',
        hint: 'Aplica la fórmula: Activos - Pasivos.',
        points: 100
    },
    {
        id: 21, topic: 'finanzas', type: 'multiple',
        question: '¿Qué representa la liquidez en el ámbito financiero?',
        options: ['La facilidad con la que un activo se puede transformar en dinero efectivo', 'El porcentaje de impuesto cobrado a las ganancias', 'El nivel de endeudamiento con el sistema financiero', 'El valor total de las maquinarias de una empresa'],
        correct: 0,
        explanation: 'La liquidez indica qué tan rápido disponible está el dinero de un bien sin perder su valor.',
        hint: 'El dinero en efectivo es el activo con mayor grado de este atributo.',
        points: 100
    },
    {
        id: 22, topic: 'credito', type: 'multiple',
        question: '¿Qué es el cobro de comisiones bancarias?',
        options: ['Cargos autorizados por la prestación de servicios financieros adicionales o de administración', 'El porcentaje legal retenido para las AFP', 'La tasa impositiva del Formulario 29', 'El dividendo mensual de una propiedad'],
        correct: 0,
        explanation: 'Son cobros por operación o mantención de productos financieros por parte de las instituciones.',
        hint: 'Se cobran por la mantención de cuentas, tarjetas o transferencias internacionales.',
        points: 100
    },
    {
        id: 23, topic: 'inversion', type: 'multiple',
        question: '¿Qué es un Depósito a Plazo (DAP)?',
        options: ['Un instrumento de inversión de renta fija con plazo y tasa de interés acordados previamente', 'Una tarjeta de crédito con cupo en dólares', 'Un fondo especulativo de criptomonedas', 'Un pago automático de cuentas básicas'],
        correct: 0,
        explanation: 'El DAP es una opción de inversión segura y predecible emitida por bancos regulados.',
        hint: 'Conoces desde el primer día la rentabilidad que obtendrás al vencimiento.',
        points: 100
    },
    {
        id: 24, topic: 'presupuesto', type: 'multiple',
        question: '¿Cuál es el beneficio de llevar una "planilla de presupuesto mensual"?',
        options: ['Tener control claro sobre el destino del dinero y prevenir sobreendeudamientos', 'Evitar automáticamente la retención de impuestos en el trabajo', 'Eliminar las deudas contraídas en el pasado de forma inmediata', 'Garantizar aumentos de sueldo anuales'],
        correct: 0,
        explanation: 'Registrar datos contables personales permite tomar decisiones informadas sobre consumo y ahorro.',
        hint: 'Aporta visibilidad a tus hábitos financieros diarios.',
        points: 100
    },
    {
        id: 25, topic: 'finanzas', type: 'multiple',
        question: '¿A qué hace referencia el interés compuesto?',
        options: ['A los intereses generados que se van sumando al capital para generar nuevos intereses', 'Al interés cobrado solo sobre el capital originario', 'A la tasa fija aplicada únicamente en la primera cuota', 'Al cobro de impuestos por transacciones bancarias'],
        correct: 0,
        explanation: 'En el interés compuesto los intereses se capitalizan periódicamente ("interés sobre interés").',
        hint: 'Efecto multiplicador que hace crecer exponencialmente una inversión con el tiempo.',
        points: 100
    }
];

// ------------------------------------------------------------
// NIVEL 1: FONDO DE EMERGENCIA Y EDUCACIÓN FINANCIERA (32 Preguntas)
// Grupo A (primeras 17): 10 nuevas + 7 rescatadas del banco anterior
// Grupo B (últimas 15): preguntas nuevas 111-125
// ------------------------------------------------------------
const fondoEmergenciaQuestions = [
    // === GRUPO A (17 preguntas) - Se elegirán 5 para las primeras posiciones ===
    { id: 101, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál es el propósito esencial de un fondo de emergencia?', options: ['Adquirir artículos de lujo en liquidación', 'Cubrir contingencias financieras imprevistas sin recurrir a deudas costosas', 'Invertir en instrumentos de alto riesgo bursátil', 'Financiar las vacaciones anuales'], correct: 1, explanation: 'Funciona como un colchón de protección ante eventualidades como desempleo, emergencias de salud o reparaciones urgentes.', hint: 'Aporta liquidez ante imprevistos para no sobreendeudarse.', points: 100 },
    { id: 102, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué situación justifica plenamente el uso del fondo de emergencia?', options: ['Un tratamiento médico no programado ni cubierto en su totalidad', 'El cambio del automóvil por un modelo del año', 'Viajes de descanso no planificados', 'Aprovechar ofertas informales de vestuario'], correct: 0, explanation: 'Un problema de salud imprevisto es una urgencia real que afecta la integridad y estabilidad.', hint: 'Diferencia eventos urgentes e inevitables de simples deseos.', points: 100 },
    { id: 103, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuántos meses de gastos fijos de subsistencia se aconseja mantener en el fondo de emergencia?', options: ['1 semana', 'Entre 3 y 6 meses', 'Mínimo 5 años', 'No se requiere un fondo previo'], correct: 1, explanation: 'Permite mantener la operatividad básica del hogar mientras se soluciona la contingencia laboral o de ingresos.', hint: 'Cubre un período intermedio de resguardo.', points: 100 },
    { id: 104, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué atributo principal debe poseer el instrumento donde se deposita el fondo de emergencia?', options: ['Alta liquidez y bajo riesgo (disponibilidad inmediata)', 'Baja liquidez y alta volatilidad', 'Cierre de giros por más de 10 años', 'Inversión exclusiva en criptoactivos'], correct: 0, explanation: 'En una emergencia el dinero debe rescatarse de forma rápida y sin pérdida de capital originario.', hint: 'Prioriza disponibilidad sobre altas rentabilidades con riesgo.', points: 100 },
    { id: 105, topic: 'fondo-emergencia', type: 'multiple', question: 'En Chile, ¿qué documento laboral detalla la liquidación del sueldo del trabajador?', options: ['Factura electrónica', 'Liquidación de sueldos', 'Orden de compra', 'Guía de despacho'], correct: 1, explanation: 'La liquidación de sueldos expone formalmente haberes, descuentos previsionales, impuestos y el líquido a pagar.', hint: 'Es el comprobante legal de la remuneración periódica.', points: 100 },
    { id: 106, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué es el "Sueldo Líquido" o "Líquido a Pagar"?', options: ['Monto retenido por las AFP', 'Monto final que percibe el trabajador tras deducciones legales', 'El sueldo base antes de los descuentos', 'La gratificación anual repartida'], correct: 1, explanation: 'Sueldo Líquido = Haberes Totales - Descuentos Legales (Previsión, Salud, Impuestos, etc.).', hint: 'Es el monto real depositado en la cuenta del trabajador.', points: 100 },
    { id: 107, topic: 'fondo-emergencia', type: 'multiple', question: 'Si una persona percibe un sueldo líquido de $600.000 y sus gastos básicos mensuales son $400.000, ¿cuánto requiere para un fondo de emergencia equivalente a 3 meses de gastos?', options: ['$1.200.000', '$1.800.000', '$600.000', '$2.400.000'], correct: 0, explanation: 'Se multiplican los gastos fijos básicos por los meses deseados ($400.000 × 3 = $1.200.000).', hint: 'Calcula sobre el monto de gastos operacionales fijos, no del sueldo total.', points: 100 },
    { id: 108, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál es la primera medida recomendada para iniciar la construcción de un ahorro constante?', options: ['Automatizar un aporte mensual a una cuenta de ahorro ni bien se recibe el ingreso', 'Esperar a fin de mes para ver si resta dinero', 'Solicitar un avance en efectivo para comenzar', 'Incrementar los cupos de tarjetas de crédito'], correct: 0, explanation: 'La estrategia "pagarse a uno mismo primero" consolida el hábito de ahorro regular.', hint: 'Considera el ahorro como un compromiso fijo al inicio del período.', points: 100 },
    { id: 109, topic: 'fondo-emergencia', type: 'multiple', question: 'En el contexto chileno, ¿dónde es prudente resguardar el fondo de emergencia?', options: ['En una Cuenta RUTA, Cuenta de Ahorro o Fondo Mutuo Money Market de bajo riesgo', 'Guardado en efectivo en la vivienda', 'En acciones especulativas de alta volatilidad', 'Prestando el monto a terceros sin contrato'], correct: 0, explanation: 'Las cuentas bancarias o fondos money market ofrecen custodia segura y rescate inmediato.', hint: 'Busca instituciones financieras reguladas por la CMF.', points: 100 },
    { id: 110, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué distingue un "deseo" de una "necesidad" financiera?', options: ['Las necesidades son indispensables para la subsistencia y las actividades básicas; los deseos son prescindibles', 'Los deseos siempre son más baratos que las necesidades', 'Las necesidades corresponden solo a compras tecnológicas', 'No existe diferencia conceptual'], correct: 0, explanation: 'Priorizar necesidades permite optimizar el uso del presupuesto y evitar fugas de capital.', hint: 'Identifica lo vital frente a lo suplementario.', points: 100 },
    // --- Preguntas rescatadas del banco anterior ---
    { id: 103b, topic: 'fondo-emergencia', type: 'multiple', question: '¿Para qué sirve un fondo de emergencia?', options: ['Comprar cosas por impulso', 'Ahorrar para vacaciones', 'Cubrir gastos inesperados sin endeudarse', 'Comprar tecnología'], correct: 2, explanation: 'Te protege de pedir préstamos con intereses altos cuando surgen imprevistos.', hint: 'Su propósito es evitar que un imprevisto te obligue a adquirir deudas costosas.', points: 100 },
    { id: 104b, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuándo es recomendable ahorrar?', options: ['Solo cuando sobra dinero', 'Todos los meses', 'Una vez al año', 'Nunca'], correct: 1, explanation: 'El ahorro es un hábito constante que se planifica cada mes, sin importar el monto.', hint: 'La constancia es más importante que la cantidad. No esperes a que "sobre" dinero para empezar.', points: 100 },
    { id: 105b, topic: 'fondo-emergencia', type: 'multiple', question: 'Si se rompe el refrigerador de tu casa, ¿qué sería lo más recomendable?', options: ['Pedir un préstamo', 'Esperar varios meses', 'Utilizar el fondo de emergencia', 'No hacer nada'], correct: 2, explanation: 'Es una urgencia doméstica para la cual está diseñado este fondo.', hint: 'Para eso creaste el fondo de emergencia: para resolver problemas sin endeudarte.', points: 100 },
    { id: 106b, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál de estas opciones NO corresponde a una emergencia?', options: ['Una operación médica', 'Una reparación urgente', 'Comprar el último modelo de celular', 'Reparar una fuga de agua'], correct: 2, explanation: 'Cambiar de teléfono por gusto es un deseo, no una emergencia.', hint: 'Diferencia entre lo que es urgente y necesario versus lo que es un simple deseo de consumo.', points: 100 },
    { id: 109b, topic: 'fondo-emergencia', type: 'multiple', question: '¿Por qué la planilla de remuneraciones puede ayudar a crear un fondo de emergencia?', options: ['Porque aumenta el sueldo', 'Porque elimina gastos', 'Porque permite saber cuánto dinero recibe una persona y cuánto puede ahorrar', 'Porque evita pagar impuestos'], correct: 2, explanation: 'Saber tus ingresos exactos permite calcular tu capacidad de ahorro mensual.', hint: 'Conocer con precisión cuánto dinero recibes es el primer paso para planificar cuánto puedes ahorrar.', points: 100 },
    { id: 110b, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál de las siguientes especialidades enseña sobre remuneraciones, educación financiera, administración y contabilidad?', options: ['🍳 Gastronomía', '👶 Atención de Párvulos', '📊 Contabilidad', '🥫 Elaboración Industrial de Alimentos', '⚡ Electrónica'], correct: 2, explanation: 'Contabilidad entrega las herramientas para administrar el dinero y las organizaciones.', hint: 'Es la especialidad que se enfoca en registrar, analizar y gestionar la información financiera.', points: 100 },
    { id: 115b, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál es el primer paso para crear un fondo de emergencia?', options: ['Calcular los gastos mensuales básicos', 'Pedir un préstamo', 'Invertir en la bolsa', 'Gastar menos en entretención'], correct: 0, explanation: 'Primero debes saber cuánto necesitas para cubrir tus gastos esenciales.', hint: 'Antes de ahorrar, necesitas saber exactamente cuánto gastas en lo esencial cada mes.', points: 100 },
    // === GRUPO B (15 preguntas) - Se elegirán 5 para las últimas posiciones ===
    { id: 111, topic: 'fondo-emergencia', type: 'multiple', question: '¿Por qué no es recomendable mantener el fondo de emergencia acumulado en dinero en efectivo en el hogar?', options: ['Por riesgos de robo, pérdidas físicas y pérdida de poder adquisitivo frente a la inflación', 'Porque los billetes caducan legalmente cada seis meses', 'Porque es ilegal poseer dinero en efectivo en la vivienda', 'Porque devenga comisiones bancarias mensuales automáticas'], correct: 0, explanation: 'El dinero físico en casa corre riesgos de seguridad y desvalorización continua por inflación.', hint: 'Evalúa los riesgos de seguridad y de desvalorización por la UF/IPC.', points: 100 },
    { id: 112, topic: 'fondo-emergencia', type: 'multiple', question: 'Si utilizas parte de tu fondo de emergencia para una reparación urgente de la vivienda, ¿cuál es el paso a seguir?', options: ['Reponer prioritariamente el dinero extraído en los siguientes presupuestos mensuales', 'Cerrar la cuenta de ahorro de inmediato', 'Solicitar un crédito adicional para celebrar el arreglo', 'Ignorar el saldo restante y no volver a ahorrar'], correct: 0, explanation: 'Tras usar el fondo por una urgencia real, la prioridad debe ser reponer el capital gastado.', hint: 'Reconstruye el escudo financiero tan pronto como sea posible.', points: 100 },
    { id: 113, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál es el principal riesgo de utilizar la tarjeta de crédito para cubrir emergencias en vez de un fondo propio?', options: ['Pagar elevados intereses financieros y adquirir compromisos que comprometen el ingreso futuro', 'Incurrir en faltas ante el Servicio de Impuestos Internos', 'Que la tarjeta pierda vigencia de forma inmediata', 'Que se descuente automáticamente del sueldo bruto del mes'], correct: 0, explanation: 'Financiar emergencias con deuda endeuda los meses venideros con altos costos de tasa de interés.', hint: 'Recurrir a crédito aumenta los gastos fijos futuros.', points: 100 },
    { id: 114, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué tipo de instrumento financiero NO es recomendable para guardar un fondo de emergencia?', options: ['Acciones de empresas emergentes de alta volatilidad bursátil', 'Cuentas de ahorro a la vista con giros incondicionales', 'Fondos mutuos conservadores de mercado monetario', 'Depósitos a plazo fijo de muy corto período (30 días)'], correct: 0, explanation: 'Las acciones volátiles pueden caer de precio justo cuando se necesite retirar el dinero.', hint: 'Evita instrumentos cuya rentabilidad fluctúe drásticamente en el corto plazo.', points: 100 },
    { id: 115, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué es la brecha de liquidez personal?', options: ['La diferencia negativa entre los ingresos disponibles inmediatos y las deudas con vencimiento a corto plazo', 'El saldo total acumulado en las administradoras de fondos de pensiones', 'El impuesto a las ventas aplicado en las transferencias electrónicas', 'El monto tope prestado en un crédito bancario'], correct: 0, explanation: 'Ocurre cuando no se cuenta con caja disponible para afrontar pagos inmediatos obligatorios.', hint: 'Relaciona tus recursos en efectivo con las deudas que vencen ya.', points: 100 },
    { id: 116, topic: 'fondo-emergencia', type: 'multiple', question: 'Si tus ingresos disminuyen de manera temporal, ¿qué rubro de gastos debes reducir en primer lugar?', options: ['Gastos prescindibles y de entretenimiento (gastos variables opcionales)', 'Arriendo o dividendo de la vivienda habitual', 'Pagos de servicios básicos como agua y electricidad', 'Cotizaciones mínimas de salud obligatoria'], correct: 0, explanation: 'Primero se recortan consumos de ocio o prescindibles para mantener protegidas las necesidades básicas.', hint: 'Identifica cuáles son gastos no esenciales en la planilla.', points: 100 },
    { id: 117, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cómo influye la inflación acumulada sobre el fondo de emergencia mantenido en una cuenta corriente tradicional que no paga intereses?', options: ['Reduce gradualmente el poder comprador real de ese dinero guardado', 'Aumenta automáticamente el saldo disponible', 'No genera impacto alguno al ser dinero protegido por el banco', 'Multiplica los intereses a tasa real'], correct: 0, explanation: 'Si la inflación sube y la cuenta paga 0% de interés, el dinero pierde poder adquisitivo.', hint: 'El IPC hace que las cosas cuesten más y tu dinero rinda menos.', points: 100 },
    { id: 118, topic: 'fondo-emergencia', type: 'multiple', question: '¿A qué se refiere el término "Sobreendeudamiento"?', options: ['Cuando las cuotas de deudas superan la capacidad real de pago del ingreso mensual', 'Ahorrar más del 50% de las remuneraciones en depósitos a plazo', 'Tener habilitadas más de dos tarjetas de débito activas', 'Cobrar sueldos imponibles por sobre el tope legal'], correct: 0, explanation: 'El sobreendeudamiento ahoga el presupuesto familiar y destruye la estabilidad económica.', hint: 'Ocurre cuando la carga de deudas absorbe casi todo el ingreso.', points: 100 },
    { id: 119, topic: 'fondo-emergencia', type: 'multiple', question: 'En la liquidación de sueldo en Chile, ¿cuál es el Sueldo Bruto u Honorario Bruto?', options: ['La suma total de todos los haberes (imponibles y no imponibles) antes de hacer deducciones de ley', 'El saldo abonado directamente en la cuenta bancaria', 'El aporte que el empleador paga a las AFP únicamente', 'El impuesto de primera categoría retenido'], correct: 0, explanation: 'Es la remuneración total convenida sobre la que luego se aplicarán los descuentos legales.', hint: 'Corresponde al monto pactado previo a las cotizaciones previsionales y de salud.', points: 100 },
    { id: 120, topic: 'fondo-emergencia', type: 'multiple', question: '¿Por qué el Seguro de Cesantía en Chile es una herramienta complementaria al fondo de emergencia?', options: ['Proporciona ingresos temporales en caso de quedar desempleado según el Código del Trabajo', 'Permite solicitar créditos de consumo sin cobrar intereses', 'Descuenta automáticamente compras de alimentos en supermercados', 'Financia en un 100% las vacaciones anuales del trabajador'], correct: 0, explanation: 'El Seguro de Cesantía gestionado por la AFC otorga prestaciones económicas en situaciones de desempleo.', hint: 'Es una protección social que entrega fondos si pierdes tu trabajo.', points: 100 },
    { id: 121, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué es la capacidad de pago personal?', options: ['El margen de dinero remanente tras restar los gastos fijos e indispensables de los ingresos totales', 'El cupo máximo concedido por una tarjeta de crédito comercial', 'La suma de todos los activos fijos poseídos a la fecha', 'El límite máximo fijado legalmente para otorgar créditos'], correct: 0, explanation: 'Muestra con cuánta holgura real se pueden asumir nuevos compromisos o planes de ahorro.', hint: 'Mide el ingreso disponible libre de compromisos vitales.', points: 100 },
    { id: 122, topic: 'fondo-emergencia', type: 'multiple', question: 'Si una persona acumula un fondo de emergencia de $1.500.000 y sus gastos básicos mensuales son de $500.000, ¿para cuántos meses de cobertura alcanza su fondo?', options: ['3 meses', '5 meses', '2 meses', '6 meses'], correct: 0, explanation: 'Cobertura = Fondo acumulado / Gastos mensuales ($1.500.000 / $500.000 = 3 meses).', hint: 'Divide el ahorro total entre el costo mensual básico de vida.', points: 100 },
    { id: 123, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué es el costo de oportunidad al decidir no ahorrar dinero para contingencias?', options: ['Tener que asumir préstamos costosos con intereses en momentos imprevistos', 'Recibir bonos especiales por parte del sistema de pensiones', 'Obtener descuentos exclusivos en compras minoristas', 'Mejorar el historial crediticio de forma automática'], correct: 0, explanation: 'No ahorrar expone a tener que pedir préstamos caros o vender activos apresuradamente cuando surge una crisis.', hint: 'Compara lo que pierdes al estar desprotegido frente a un imprevisto.', points: 100 },
    { id: 124, topic: 'fondo-emergencia', type: 'multiple', question: '¿Qué caracteriza a un gasto inesperado pero planificable?', options: ['Eventos anuales o semestrales previsibles, como la revisión técnica del vehículo o la patente', 'Pérdida inesperada del trabajo por quiebra laboral', 'Enfermedad catastrófica repentina', 'Terremoto o catástrofe natural'], correct: 0, explanation: 'Aunque ocurren esporádicamente, se conoce su existencia futura y deben provisionarse mes a mes.', hint: 'Son gastos periódicos conocidos que no suceden todos los meses.', points: 100 },
    { id: 125, topic: 'fondo-emergencia', type: 'multiple', question: '¿Cuál es el primer paso práctico para recortar presupuestariamente deudas descontroladas?', options: ['Listar todas las deudas con sus tasas de interés y priorizar el pago de las más costosas', 'Ignorar las notificaciones de los acreedores', 'Solicitar un nuevo crédito con mayor tasa para pagar el anterior', 'Gastar los ahorros reservados en consumos recreativos'], correct: 0, explanation: 'Consolidar el mapa de deudas permite aplicar estrategias como el método avalancha (pagar el interés más alto primero).', hint: 'Organiza y visualiza los saldos exigibles y sus intereses asociados.', points: 100 }
];

// ------------------------------------------------------------
// NIVEL 2: CONTABILIDAD GENERAL Y LEGISLACIÓN TRIBUTARIA/LABORAL (25 Preguntas)
// ------------------------------------------------------------
const nivel2Questions = [
    { id: 201, topic: 'contabilidad', type: 'multiple', question: 'Si una empresa vende mercaderías por $500.000 al contado, ¿cuál es el registro contable de la entrada de recursos?', options: ['Débito (Carga) a Caja/Banco y Crédito (Abona) a Ingresos por Ventas', 'Carga a Ingresos por Ventas y Abona a Caja', 'Carga a Proveedores y Abona a Costo de Ventas', 'Carga a Capital y Abona a Banco'], correct: 0, explanation: 'El activo disponible aumenta en el Debe (Caja) e incrementa las cuentas de Ingreso en el Haber.', hint: 'Registra el aumento de liquidez y el reconocimiento del ingreso.', points: 150 },
    { id: 202, topic: 'tributacion', type: 'multiple', question: 'En Chile, ¿cuál es la tasa vigente del Impuesto al Valor Agregado (IVA)?', options: ['19%', '16%', '15%', '21%'], correct: 0, explanation: 'La tasa general de IVA aplicable a las ventas de bienes y servicios en Chile es del 19%.', hint: 'Aplica a la gran mayoría de las transacciones comerciales en el país.', points: 150 },
    { id: 203, topic: 'tributacion', type: 'multiple', question: '¿Qué representa el "Crédito Fiscal IVA" para un contribuyente comerciante?', options: ['El IVA soportado y pagado en las compras y adquisiciones del giro', 'El IVA recargado a los clientes en las facturas de venta', 'Un impuesto de retención a la renta de los trabajadores', 'El pago total mensual por patentes municipales'], correct: 0, explanation: 'El Crédito Fiscal es el IVA pagado a proveedores, el cual reduce la obligación tributaria neta ante el SII.', hint: 'Corresponde al IVA pagado al adquirir insumos o mercadería.', points: 150 },
    { id: 204, topic: 'tributacion', type: 'multiple', question: 'Si una empresa genera $380.000 en Débito Fiscal y posee $200.000 en Crédito Fiscal en el mes, ¿cuánto IVA debe declarar y pagar en el Formulario 29 (F29)?', options: ['$180.000', '$580.000', '$200.000', '$0 (Le queda remanente)'], correct: 0, explanation: 'IVA a Pagar = Débito Fiscal - Crédito Fiscal ($380.000 - $200.000 = $180.000).', hint: 'Resta el IVA pagado en compras del IVA cobrado en ventas.', points: 150 },
    { id: 205, topic: 'nomina', type: 'multiple', question: 'En Chile, ¿cuál de los siguientes ítems se considera un Haber NO Imponible en la liquidación de sueldo?', options: ['Asignación de movilización y colación', 'Sueldo Base', 'Horas Extraordinarias', 'Comisiones por ventas'], correct: 0, explanation: 'Las asignaciones de colación, movilización y pérdida de caja compensan gastos del trabajo y no constituyen remuneración imponible.', hint: 'Son montos destinados a cubrir gastos de traslado y alimentación operativos.', points: 150 },
    { id: 206, topic: 'contabilidad', type: 'multiple', question: 'Las cuentas contables del grupo PASIVO presentan habitualmente una naturaleza de saldo:', options: ['Acreedora (nacen y aumentan por el Haber)', 'Deudora (nacen y aumentan por el Debe)', 'Neutro sin variaciones', 'Exclusivamente variable en el activo'], correct: 0, explanation: 'Los Pasivos (obligaciones con terceros) y el Patrimonio se incrementan a través del Haber.', hint: 'Representan deudas y financiamiento externo.', points: 150 },
    { id: 207, topic: 'contabilidad', type: 'multiple', question: '¿Qué función cumple el Libro Diario en el ciclo contable?', options: ['Cronológicamente registrar de día en día todas las operaciones financieras', 'Resumir el saldo final de cada cuenta al cierre del año', 'Listar los datos de contacto de los trabajadores', 'Controlar la asistencia diaria del personal'], correct: 0, explanation: 'En el Libro Diario se anotan los asientos de cada transacción en estricto orden cronológico.', hint: 'Es el libro obligatorio de registro diario.', points: 150 },
    { id: 208, topic: 'nomina', type: 'multiple', question: 'En el sistema de previsión chileno, ¿a cuánto equivale el descuento legal obligatorio para la cuenta de capitalización individual (AFP)?', options: ['10% de la remuneración imponible (más comisión de la AFP)', '7% de la remuneración imponible', '0.6% de la remuneración imponible', '19% del sueldo bruto'], correct: 0, explanation: 'El aporte obligatorio al fondo de pensiones es del 10% imponible base, adicional a la comisión de la administradora.', hint: 'Es el porcentaje directo a la cuenta individual de pensiones.', points: 150 },
    { id: 209, topic: 'nomina', type: 'multiple', question: '¿Cuál es el porcentaje legal mínimo retenido para el sistema de Salud (Fonasa o Isapre) sobre el total imponible?', options: ['7%', '10%', '12%', '19%'], correct: 0, explanation: 'El cotizante debe destinar obligatoriamente al menos un 7% imponible para cobertura de salud.', hint: 'Porcentaje fijado por ley para la cotización de salud.', points: 150 },
    { id: 210, topic: 'contabilidad', type: 'multiple', question: '¿A qué principio responde la regla: "Toda transacción afecta al menos a dos cuentas manteniendo la igualdad de cargos y abonos"?', options: ['Principio de Partida Doble', 'Principio de Caja Estricta', 'Criterio de Devengado Proporcional', 'Valor Histórico Reajustado'], correct: 0, explanation: 'La Partida Doble es la base del registro contable: No hay deudor sin acreedor.', hint: 'Garantiza el balance estricto entre el Debe y el Haber.', points: 150 },
    { id: 211, topic: 'tributacion', type: 'multiple', question: '¿Qué documento tributario emite en Chile un profesional independiente que presta servicios de asesoría?', options: ['Boleta de Honorarios Electrónica', 'Factura de Venta Afecta', 'Guía de Despacho', 'Nota de Crédito'], correct: 0, explanation: 'Los profesionales independientes que emiten rentas de segunda categoría utilizan Boletas de Honorarios.', hint: 'Aplica para trabajadores independientes sin relación de dependencia laboral.', points: 150 },
    { id: 212, topic: 'tributacion', type: 'multiple', question: '¿Cuál es el impuesto mensual que declara una PYME en Chile mediante el Formulario 29 (F29)?', options: ['El IVA y las retenciones del impuesto a la renta (PPM, honorarios)', 'El impuesto a la herencia y donaciones', 'Las contribuciones de bienes raíces territoriales', 'El impuesto a los combustibles únicamente'], correct: 0, explanation: 'El F29 del SII recopila el IVA (Débito y Crédito) más los Pagos Provisionales Mensuales (PPM).', hint: 'Es la declaración tributaria mensual obligatoria de las empresas.', points: 150 },
    { id: 213, topic: 'contabilidad', type: 'multiple', question: '¿Cuál es la función principal del Libro Mayor?', options: ['Agrupar los movimientos por cada cuenta contable para conocer sus saldos individuales', 'Registrar la entrada y salida física de mercaderías del bodeguero', 'Archivar los contratos firmados por la empresa', 'Listar cronológicamente las transacciones diarias'], correct: 0, explanation: 'El Libro Mayor acumula los débitos y créditos de cada cuenta en particular (cuentas T).', hint: 'Consolida la información de cada cuenta individualizada.', points: 150 },
    { id: 214, topic: 'nomina', type: 'multiple', question: 'En el Código del Trabajo en Chile, ¿cómo se pagan las Horas Extraordinarias imponibles?', options: ['Con un recargo mínimo del 50% sobre el sueldo convenido para la jornada ordinaria', 'Al mismo valor que la hora ordinaria regular', 'Con un recargo del 10% obligatorio por ley', 'Se compensan únicamente con días de vacaciones'], correct: 0, explanation: 'Las horas extraordinarias se pagan con un recargo del 50% sobre el valor hora ordinario.', hint: 'Recuerda el factor legal de recargo por sobretiempo.', points: 150 },
    { id: 215, topic: 'tributacion', type: 'multiple', question: '¿Qué documento tributario modifica o anula los valores de una Factura Electrónica previa?', options: ['Nota de Crédito Electrónica', 'Guía de Despacho', 'Boleta de Ventas en Papel', 'Certificado de Retención'], correct: 0, explanation: 'La Nota de Crédito rebaja, descuenta o anula montos facturados previamente.', hint: 'Permite corregir o anular montos emitidos en facturas.', points: 150 },
    { id: 216, topic: 'contabilidad', type: 'multiple', question: 'Las cuentas contables de Gasto o Pérdida tienen una naturaleza de saldo:', options: ['Deudora (nacen y aumentan por el Debe)', 'Acreedora (nacen y aumentan por el Haber)', 'Sin saldo al cierre del ciclo', 'Exclusivamente neutra'], correct: 0, explanation: 'Los gastos, costos y activos incrementan su saldo mediante anotaciones en el Debe.', hint: 'Registran consumos de recursos que reducen el patrimonio.', points: 150 },
    { id: 217, topic: 'nomina', type: 'multiple', question: '¿Qué es el Seguro de Cesantía aportado a la AFC en contratos indefinidos?', options: ['Un descuento al trabajador (0,6%) y un aporte del empleador (2,4%) sobre la remuneración imponible', 'Un aporte financiado al 100% por el Ministerio de Hacienda', 'Un impuesto de retención que cobra la municipalidad local', 'Una cotización cobrada solo en contratos a plazo fijo'], correct: 0, explanation: 'En contratos indefinidos la cotización es compartida entre el trabajador (0,6%) y el empleador (2,4%).', hint: 'Consta de un aporte compartido entre empleado y empleador.', points: 150 },
    { id: 218, topic: 'tributacion', type: 'multiple', question: '¿Qué es el PPM (Pago Provisional Mensual) en Chile?', options: ['Un provisión mensual a cuenta del impuesto anual a la renta que debe pagar la empresa', 'El pago obligatorio del IVA en el comercio informal', 'Una retención directa realizada por Fonasa', 'El cobro municipal por patentes comerciales en línea'], correct: 0, explanation: 'El PPM es un abono mensual que hace la empresa para cubrir el Impuesto a la Renta anual (F22).', hint: 'Es un abono anticipado para el impuesto anual a la renta.', points: 150 },
    { id: 219, topic: 'contabilidad', type: 'multiple', question: '¿Qué es el Balance de Comprobación y de Saldos?', options: ['Un informe que verifica que la suma de los débitos sea igual a la suma de los créditos', 'El documento formal para pedir préstamos en un banco comercial', 'La declaración jurada enviada a los inversionistas extranjeros', 'Un catálogo de precios impreso para los vendedores'], correct: 0, explanation: 'Comprueba el cumplimiento de la partida doble en los registros del Libro Mayor.', hint: 'Verifica la igualdad aritmética entre el Debe y el Haber.', points: 150 },
    { id: 220, topic: 'nomina', type: 'multiple', question: '¿Qué representa la Gratificación Legal en la liquidación de sueldos?', options: ['La parte de las utilidades de la empresa con que se beneficia al trabajador según el Código del Trabajo', 'Un bono voluntario concedido en fiestas patrias', 'La devolución del IVA en compras de vestuario laboral', 'El viático abonado para traslados corporativos'], correct: 0, explanation: 'Es una parte de los beneficios líquidos de la empresa asignada por ley a los trabajadores.', hint: 'Suele pagarse mensualmente con tope del 4,75 ingresos mínimos.', points: 150 },
    { id: 221, topic: 'tributacion', type: 'multiple', question: '¿Qué es el Remanente de Crédito Fiscal IVA?', options: ['El exceso de Crédito Fiscal sobre el Débito Fiscal en un mes determinado, acumulable para el mes siguiente', 'Una multa impuesta por presentar la declaración con atraso', 'El monto que el SII deposita en efectivo a la empresa mensualmente', 'La exención tributaria asignada a bienes de primera necesidad'], correct: 0, explanation: 'Si las compras generan más IVA que las ventas, la diferencia se guarda como crédito para el mes posterior.', hint: 'Sucede cuando el IVA de las compras supera al IVA de las ventas.', points: 150 },
    { id: 222, topic: 'contabilidad', type: 'multiple', question: '¿A qué grupo contable pertenece la cuenta "Proveedores"?', options: ['Pasivo Corriente', 'Activo Corriente', 'Gastos Operacionales', 'Patrimonio Neto'], correct: 0, explanation: 'Representa obligaciones contraídas por adquisiciones a crédito de mercaderías o insumos a corto plazo.', hint: 'Corresponde a deudas con quienes abastecen de existencias a la empresa.', points: 150 },
    { id: 223, topic: 'contabilidad', type: 'multiple', question: '¿A qué grupo contable pertenece la cuenta "Clientes" o "Cuentas por Cobrar"?', options: ['Activo Corriente', 'Pasivo No Corriente', 'Ingresos por Ventas', 'Gastos de Administración'], correct: 0, explanation: 'Son derechos de cobro a favor de la empresa surgidos por ventas a crédito comercial.', hint: 'Son recursos pendientes de cobro originados por ventas comerciales.', points: 150 },
    { id: 224, topic: 'nomina', type: 'multiple', question: 'En una liquidación de sueldo, ¿cuál de los siguientes ítems forma parte del Total Imponible?', options: ['Sueldo Base, Horas Extras, Comisiones y Gratificación', 'Asignación de Colación y Movilización', 'Viáticos de representación y devolución de gastos de herramientas', 'Subsidio por incapacidad laboral pagado directamente'], correct: 0, explanation: 'El Total Imponible agrupa las remuneraciones directas sobre las que se calculan leyes sociales.', hint: 'Incluye la contraprestación directa por el trabajo contratado.', points: 150 },
    { id: 225, topic: 'tributacion', type: 'multiple', question: '¿Qué plataforma pública centraliza en Chile el pago de cotizaciones previsionales de los trabajadores?', options: ['Previred', 'Sence', 'ChileAtiende', 'Tesorería General de la República'], correct: 0, explanation: 'Previred es la plataforma web estándar para la declaración y pago de cotizaciones previsionales.', hint: 'Plataforma empleada para pagar AFP, Fonasa e Isapres en un solo lugar.', points: 150 }
];

// ------------------------------------------------------------
// NIVEL 3: ESTADOS FINANCIEROS, INVENTARIOS Y ANÁLISIS FINANCIERO (25 Preguntas)
// ------------------------------------------------------------
const nivel3Questions = [
    { id: 301, topic: 'estados-financieros', type: 'multiple', question: '¿Cómo se determina la Utilidad Bruta en el Estado de Resultados?', options: ['Ingresos por Ventas - Costo de Ventas', 'Ingresos Totales - Gastos Financieros', 'Activo Corriente - Pasivo Corriente', 'Utilidad Operacional + Impuestos de Primera Categoría'], correct: 0, explanation: 'La Utilidad Bruta resulta de restar el costo directo de lo vendido a los ingresos por ventas.', hint: 'Refleja el margen directo de comercialización o producción.', points: 200 },
    { id: 302, topic: 'analisis-financiero', type: 'slider', question: 'Si el Activo Corriente de una Pyme es de $12.000.000 y su Pasivo Corriente es de $4.000.000, ¿cuál es su Razón de Liquidez Corriente?', min: 0, max: 5, correctAnswer: 3, tolerance: 0, explanation: 'Liquidez Corriente = Activo Corriente / Pasivo Corriente = $12.000.000 / $4.000.000 = 3,0.', hint: 'Divide el activo de corto plazo por el pasivo de corto plazo.', points: 200 },
    { id: 303, topic: 'inventario', type: 'multiple', question: 'Bajo el método de inventario PEPS (Primero en Entrar, Primero en Salir), en contexto de inflación de costos:', options: ['El Costo de Ventas resulta menor y la Utilidad del período se presenta más alta', 'El Costo de Ventas se eleva y disminuyen los utilidades', 'No se genera impacto en la valoración final de las existencias', 'El inventario final queda subvalorado'], correct: 0, explanation: 'Como se costean primero las unidades más antiguas (más baratas), el costo de ventas disminuye y la utilidad contable sube.', hint: 'Analiza qué unidades más antiguas se imputan a ventas.', points: 200 },
    { id: 304, topic: 'estados-financieros', type: 'multiple', question: 'En la clasificación del Balance General, los Pasivos Exigibles a un plazo menor de un año son:', options: ['Pasivos Corrientes o a Corto Plazo', 'Pasivos No Corrientes o a Largo Plazo', 'Patrimonio Neto', 'Activos Intangibles'], correct: 0, explanation: 'Las deudas con vencimiento menor o igual a 12 meses forman el Pasivo Corriente.', hint: 'Obligaciones operativas de liquidación inmediata.', points: 200 },
    { id: 305, topic: 'analisis-financiero', type: 'multiple', question: '¿Cómo se calcula el Capital de Trabajo Neto Operativo?', options: ['Activo Corriente - Pasivo Corriente', 'Activo Total - Pasivo Total', 'Patrimonio - Gastos de Administración', 'Flujo de Caja Imponible + Deuda'], correct: 0, explanation: 'El Capital de Trabajo mide el margen de liquidez disponible para la operación continuada.', hint: 'Resta obligaciones de corto plazo a los activos de disponibilidad cercana.', points: 200 },
    { id: 306, topic: 'estados-financieros', type: 'multiple', question: '¿Qué representa la "Depreciación Acumulada" en el Balance General?', options: ['Una cuenta complementaria de activo que refleja el desgaste acumulado del activo fijo', 'Un compromiso de pago en efectivo al SII', 'Un ingreso extraordinario generado por venta de maquinaria', 'Un fondo en efectivo reservado en el banco'], correct: 0, explanation: 'Reduce el valor en libros de los activos fijos tangibles por uso, obsolescencia o paso del tiempo.', hint: 'Ajusta el valor original de los activos físicos de la empresa.', points: 200 },
    { id: 307, topic: 'inventario', type: 'multiple', question: 'El método de valoración del Costo Promedio Ponderado (CPP) en existencias calcula:', options: ['Un costo unitario medio dividiendo el costo total de unidades disponibles entre el total de unidades en stock', 'Asignación directa de las compras más recientes a las primeras ventas', 'Estimación subjetiva según el precio de reemplazo', 'Valoración al precio de venta final'], correct: 0, explanation: 'El CPP promedia los valores de adquisición suavizando fluctuaciones de precios.', hint: 'Determina una media ponderada tras cada compra de existencias.', points: 200 },
    { id: 308, topic: 'analisis-financiero', type: 'multiple', question: 'Si una empresa obtiene una Utilidad Neta de $5.000.000 con Ventas Totales de $25.000.000, ¿cuál es su Margen Neto de Ganancia?', options: ['20%', '25%', '15%', '50%'], correct: 0, explanation: 'Margen Neto = (Utilidad Neta / Ventas Totales) × 100 = ($5.000.000 / $25.000.000) × 100 = 20%.', hint: 'Divide la utilidad final entre las ventas y multiplica por 100.', points: 200 },
    { id: 309, topic: 'estados-financieros', type: 'multiple', question: '¿Qué diferencia clave existe entre el Balance General y el Estado de Resultados?', options: ['El Balance General muestra la situación a una fecha determinada; el Estado de Resultados refleja el desempeño en un período', 'El Estado de Resultados es un reporte estático y el Balance es un flujo', 'El Balance solo incluye las deudas con bancos y el Estado de Resultados los impuestos', 'No presentan diferencias de fondo'], correct: 0, explanation: 'El Balance es una "fotografía" del patrimonio a una fecha; el Estado de Resultados es una "película" de flujos del período.', hint: 'Diferencia informes de carácter estático frente a dinámicos.', points: 200 },
    { id: 310, topic: 'estados-financieros', type: 'multiple', question: 'En el Estado de Resultados, ¿dónde se ubican los sueldos del personal de administración y el arriendo de las oficinas corporativas?', options: ['Gastos de Administración y Ventas (Gastos Operacionales)', 'Costo Directo de Ventas', 'Ingresos No Operacionales', 'Activo Intangible diferido'], correct: 0, explanation: 'Constituyen gastos de apoyo logístico y operacional general que no están integrados directamente en el costo de producción.', hint: 'Desembolsos necesarios para mantener la infraestructura y gestión corporativa.', points: 200 },
    { id: 311, topic: 'analisis-financiero', type: 'multiple', question: '¿Qué mide el Ratio de Endeudamiento sobre el Patrimonio (Pasivo Total / Patrimonio)?', options: ['La proporción de financiamiento proveniente de acreedores respecto al capital aportado por los dueños', 'El margen bruto dejado por cada venta individual', 'El número de días promedio en que se recupera la cobranza', 'La rentabilidad del activo total'], correct: 0, explanation: 'Indica el grado de apalancamiento financiero e independencia de la empresa frente a terceros.', hint: 'Mide la dependencia financiera de la empresa respecto de sus acreedores.', points: 200 },
    { id: 312, topic: 'inventario', type: 'multiple', question: '¿Qué es la Tarjeta Existencias o Kardex de Inventario?', options: ['Un registro auxiliar donde se anotan detalladamente las entradas, salidas y saldos físicos y valorizados de mercadería', 'Una tarjeta prepago para compras corporativas', 'El comprobante bancario emitido tras pagar cotizaciones', 'La ficha de contrato del personal de bodega'], correct: 0, explanation: 'El Kardex permite controlar en todo momento las unidades físicas y los costos asociados de las existencias.', hint: 'Lleva el control de unidades y valores de cada producto en stock.', points: 200 },
    { id: 313, topic: 'estados-financieros', type: 'multiple', question: '¿Qué información entrega el Estado de Flujos de Efectivo?', options: ['El origen y uso real del dinero en efectivo durante el período (operación, inversión y financiamiento)', 'Las utilidades devengadas pendientes de cobro a clientes', 'El avalúo fiscal de las propiedades de la empresa', 'El número de productos en stock al cierre del ejercicio'], correct: 0, explanation: 'Muestra los movimientos reales de entradas y salidas de caja y bancos divididos en tres áreas.', hint: 'Clasifica las variaciones de caja en Operación, Inversión y Financiamiento.', points: 200 },
    { id: 314, topic: 'analisis-financiero', type: 'multiple', question: '¿Cómo se define la "Prueba Ácida" o Razón Ácida de liquidez?', options: ['(Activo Corriente - Inventarios) / Pasivo Corriente', 'Activo Total / Pasivo Total', 'Utilidad Neta / Capital Social', 'Caja / Pasivo No Corriente'], correct: 0, explanation: 'Es un test estricto de liquidez que descuenta los inventarios por ser el activo corriente menos líquido.', hint: 'Aísla las existencias del activo corriente antes de dividir.', points: 200 },
    { id: 315, topic: 'estados-financieros', type: 'multiple', question: '¿Qué son las IFRS (NIIF) en el ámbito contable?', options: ['Normas Internacionales de Información Financiera para homogenizar la contabilidad global', 'Impuestos de importación aplicados en aduanas chilenas', 'Leyes chilenas aplicadas exclusivamente a trabajadores contratados', 'Sistemas de fiscalización interna del Servicio de Tesorería'], correct: 0, explanation: 'Son los estándares internacionales adoptados en Chile para la presentación transparente de Estados Financieros.', hint: 'Estándar contable internacional adoptado en nuestro país.', points: 200 },
    { id: 316, topic: 'analisis-financiero', type: 'multiple', question: '¿Qué indica una Razón de Liquidez Corriente menor a 1,0 en una empresa?', options: ['Que la empresa podría enfrentar dificultades para cumplir sus obligaciones de corto plazo', 'Que la empresa posee un exceso de fondos en efectivo sin rentabilizar', 'Que los accionistas recibieron un reparto extraordinario de dividendos', 'Que no posee deudas comerciales registradas'], correct: 0, explanation: 'Significa que los pasivos corrientes superan a los activos corrientes disponibles en el corto plazo.', hint: 'Tener menos de $1 en activos corrientes por cada $1 de deuda a corto plazo.', points: 200 },
    { id: 317, topic: 'estados-financieros', type: 'multiple', question: '¿A qué categoría pertenece la cuenta "Maquinarias" en el Balance General?', options: ['Activo No Corriente (Activo Fijo Tangible)', 'Activo Corriente', 'Pasivo No Corriente', 'Gastos Financieros'], correct: 0, explanation: 'Son bienes tangibles permanentes destinados a la producción y no a la venta inmediata.', hint: 'Son bienes duraderos necesarios para la infraestructura productiva.', points: 200 },
    { id: 318, topic: 'inventario', type: 'multiple', question: 'Bajo el método UEPS (Último en Entrar, Primero en Salir) —prohibido por IFRS pero estudiado teóricamente—:', options: ['Las últimas unidades adquiridas son las primeras en imputarse al Costo de Ventas', 'Las primeras unidades compradas se imputan al costo de la venta', 'Las existencias quedan valorizadas al precio de mercado futuro', 'No se realiza valoración financiera de stocks'], correct: 0, explanation: 'UEPS asigna las compras más recientes al costo de ventas.', hint: 'Consume primero las compras más recientes.', points: 200 },
    { id: 319, topic: 'analisis-financiero', type: 'multiple', question: '¿Qué es el ROE (Return on Equity)?', options: ['Rentabilidad sobre el Patrimonio Neto (Utilidad Neta / Patrimonio)', 'Rentabilidad del producto sobre su precio de costo', 'Razón de endeudamiento a largo plazo bancario', 'Retención obligatoria en boletas de honorarios'], correct: 0, explanation: 'Mide la rentabilidad generada por la empresa sobre el capital invertido por los propietarios.', hint: 'Mide el retorno obtenido por los dueños sobre su capital.', points: 200 },
    { id: 320, topic: 'estados-financieros', type: 'multiple', question: 'En el Estado de Resultados, ¿qué resta viene inmediatamente después de la Utilidad Operacional?', options: ['Gastos Financieros e Impuestos', 'Costo de Ventas', 'Devoluciones sobre ventas', 'Ingresos de explotación directos'], correct: 0, explanation: 'De la utilidad operacional se restan los costos de financiamiento (intereses) y los impuestos corporativos.', hint: 'Considera los costos de financiamiento e impuestos a las utilidades.', points: 200 },
    { id: 321, topic: 'analisis-financiero', type: 'multiple', question: '¿Qué es la Rotación de Inventarios?', options: ['El número de veces que el inventario se vende y se repone en un período', 'La velocidad de depreciación de las maquinarias de la planta', 'El traslado físico de mercadería entre bodegas sucursales', 'El vencimiento de los productos perecibles en mostrador'], correct: 0, explanation: 'Indica la eficiencia en la gestión del stock: cuántas veces "gira" el inventario en el año.', hint: 'Mide la rapidez con que las existencias se convierten en ventas.', points: 200 },
    { id: 322, topic: 'estados-financieros', type: 'multiple', question: '¿Qué son los Gastos Pagados por Adelantado (como un arriendo anual pagado en enero)?', options: ['Activos Corrientes (Derechos a recibir un servicio futuro)', 'Pasivos Exigibles', 'Gastos devengados e irrecuperables', 'Patrimonio de los accionistas'], correct: 0, explanation: 'Representan un derecho a recibir un beneficio futuro, por lo que se consideran activos corrientes.', hint: 'Al haberse pagado antes de consumir el servicio, representan un derecho.', points: 200 },
    { id: 323, topic: 'analisis-financiero', type: 'multiple', question: '¿Qué mide la Rotación de Cuentas por Cobrar?', options: ['La velocidad o frecuencia con que la empresa cobra las ventas realizadas a crédito', 'El cobro adicional de intereses moratorios a clientes', 'El plazo en que la empresa liquida deudas con proveedores', 'El volumen total de facturas emitidas en el año'], correct: 0, explanation: 'Mide la efectividad del área de crédito y cobranzas en convertir las ventas en caja.', hint: 'Muestra la rapidez con que las facturas emitidas a clientes se convierten en caja.', points: 200 },
    { id: 324, topic: 'estados-financieros', type: 'multiple', question: '¿Qué son las Provisiones en la contabilidad corporativa?', options: ['Pasivos de cuantía o fecha incierta constituidos para cubrir obligaciones probables', 'Mermas físicas de productos en la bodega de almacenamiento', 'Fondo permanente de efectivo resguardado por el cajero', 'Aportes futuros exigidos a los nuevos socios'], correct: 0, explanation: 'Las provisiones son pasivos reconocidos para anticipar gastos u obligaciones probables.', hint: 'Reconocen pasivos probables antes de conocer la fecha o monto final exacto.', points: 200 },
    { id: 325, topic: 'analisis-financiero', type: 'multiple', question: '¿Qué indica el indicador ROA (Return on Assets)?', options: ['La eficiencia de la empresa para generar utilidades utilizando sus Activos Totales', 'El nivel de endeudamiento a corto plazo con proveedores', 'La tasa de retorno promedio de un depósito a plazo', 'El pago proporcional de Dividendos por Acción'], correct: 0, explanation: 'ROA = Utilidad Neta / Activos Totales; demuestra la efectividad en el uso de la infraestructura.', hint: 'Relaciona las utilidades con la totalidad de los recursos y bienes de la empresa.', points: 200 }
];

// ------------------------------------------------------------
// NIVEL 4: CÁLCULOS AVANZADOS Y APLICADOS (25 Preguntas)
// ------------------------------------------------------------
const nivelAvanzadoQuestions = [
    { id: 401, topic: 'contabilidad', type: 'multiple', question: 'Una empresa posee Activos Totales por $60.000.000 y Pasivos Totales por $22.000.000. Si los socios realizan un nuevo aporte de capital de $8.000.000 en efectivo, ¿cuál es el nuevo valor del Patrimonio?', options: ['$46.000.000', '$38.000.000', '$68.000.000', '$30.000.000'], correct: 0, explanation: 'Patrimonio Inicial = Activo - Pasivo ($60M - $22M = $38M). Patrimonio Nuevo = $38M + $8M = $46.000.000.', hint: 'Calcula primero el Patrimonio inicial con la ecuación contable y suma la inyección de capital.', points: 250 },
    { id: 402, topic: 'tributacion', type: 'multiple', question: 'Ventas Netas afectas a IVA por $2.000.000 (más 19% IVA) y Compras Netas afectas por $1.200.000 (más 19% IVA). ¿Cuál es el pago neto por concepto de IVA a declarar?', options: ['$152.000', '$380.000', '$228.000', '$608.000'], correct: 0, explanation: 'Débito Fiscal = $2.000.000 × 0,19 = $380.000. Crédito Fiscal = $1.200.000 × 0,19 = $228.000. IVA Neto a Pagar = $380.000 - $228.000 = $152.000.', hint: 'Aplica el 19% a ambos valores netos y calcula la diferencia entre Débito y Crédito.', points: 250 },
    { id: 403, topic: 'estados-financieros', type: 'multiple', question: 'Se adquiere una camioneta de reparto por $15.000.000. Se estima una vida útil de 5 años y un valor residual de $3.000.000. Bajo método lineal, ¿cuál es el valor neto en libros al finalizar el año 2?', options: ['$10.200.000', '$12.000.000', '$9.000.000', '$7.800.000'], correct: 0, explanation: 'Depreciación Anual = ($15.000.000 - $3.000.000) / 5 = $2.400.000 por año. Depreciación Acumulada (2 años) = $4.800.000. Valor en Libros = $15.000.000 - $4.800.000 = $10.200.000.', hint: 'Calcula la cuota de depreciación anual sobre el valor depreciable (Costo - Valor Residual).', points: 250 },
    { id: 404, topic: 'analisis-financiero', type: 'slider', question: 'Activo Corriente = $20.000.000, Inventarios = $8.000.000, Pasivo Corriente = $8.000.000. ¿Cuál es el indicador de la Prueba Ácida?', min: 0, max: 5, correctAnswer: 1.5, tolerance: 0.1, explanation: 'Prueba Ácida = (Activo Corriente - Inventarios) / Pasivo Corriente = ($20.000.000 - $8.000.000) / $8.000.000 = 1,5.', hint: 'Excluye las existencias por su menor liquidez antes de dividir por el pasivo corriente.', points: 250 },
    { id: 405, topic: 'analisis-financiero', type: 'multiple', question: 'Ventas Totales = $100.000.000, Costo de Ventas = $60.000.000, Gastos Operacionales = $25.000.000. ¿Cuál es el Margen Operacional de la empresa?', options: ['15%', '40%', '25%', '35%'], correct: 0, explanation: 'Utilidad Operacional = $100M - $60M - $25M = $15M. Margen Operacional = ($15M / $100M) × 100 = 15%.', hint: 'Descuenta costos y gastos operacionales de los ingresos y calcula el porcentaje sobre ventas.', points: 250 },
    { id: 406, topic: 'nomina', type: 'multiple', question: 'Un trabajador posee un Sueldo Base de $700.000 y Horas Extras por $100.000. Si sus descuentos previsionales legales obligatorios (AFP + Salud + Seguro Cesantía) suman un 18.1% de su Imponible, ¿cuál es su Sueldo Líquido (asumiendo que no paga impuesto a la renta ni tiene asignaciones no imponibles)?', options: ['$655.200', '$573.300', '$700.000', '$800.000'], correct: 0, explanation: 'Total Imponible = $700.000 + $100.000 = $800.000. Descuentos = $800.000 × 0,181 = $144.800. Sueldo Líquido = $800.000 - $144.800 = $655.200.', hint: 'Suma todos los haberes imponibles y descuenta el porcentaje previsional correspondiente.', points: 250 },
    { id: 407, topic: 'inventarios', type: 'multiple', question: 'Movimiento de Existencias (PEPS): Inventario Inicial 10 unidades a $5.000 c/u. Compra 20 unidades a $7.000 c/u. Se venden 15 unidades. ¿Cuál es el Costo de Ventas aplicado?', options: ['$85.000', '$105.000', '$75.000', '$95.000'], correct: 0, explanation: 'Bajo PEPS se consumen primero las más antiguas: (10 unidades × $5.000 = $50.000) + (5 unidades × $7.000 = $35.000). Total = $85.000.', hint: 'Agota en primer lugar el stock originario antes de valorar al costo de la nueva compra.', points: 250 },
    { id: 408, topic: 'inventarios', type: 'multiple', question: 'Mismos datos del ejercicio anterior (10u a $5.000 y 20u a $7.000). Bajo el método de Costo Promedio Ponderado (CPP), ¿cuál es el costo unitario medio de cada unidad en stock?', options: ['$6.333', '$6.000', '$7.000', '$5.500'], correct: 0, explanation: 'Costo Total = (10×$5.000) + (20×$7.000) = $50.000 + $140.000 = $190.000. Total Unidades = 30. CPP Unitario = $190.000 / 30 = $6.333,33.', hint: 'Suma el valor total acumulado y divídelo entre el stock físico total disponible.', points: 250 },
    { id: 409, topic: 'matematica-financiera', type: 'multiple', question: 'Se solicita un préstamo a 6 meses por un monto de $2.000.000 con una tasa de interés simple anual del 12%. ¿Cuál es el valor total a cancelar al vencimiento?', options: ['$2.120.000', '$2.240.000', '$2.060.000', '$2.180.000'], correct: 0, explanation: 'Tasa semestral (6 meses) = 12% / 2 = 6%. Interés = $2.000.000 × 0,06 = $120.000. Total = $2.000.000 + $120.000 = $2.120.000.', hint: 'Proporciona la tasa de interés anual al período real de 6 meses (medio año).', points: 250 },
    { id: 410, topic: 'nomina', type: 'multiple', question: 'Un empleado tiene un Sueldo Imponible de $900.000 y recibe una Asignación de Movilización (no imponible) de $60.000. Si sus deducciones de previsión equivalen al 18% del imponible, ¿cuál es su sueldo líquido abonado?', options: ['$798.000', '$738.000', '$858.000', '$960.000'], correct: 0, explanation: 'Descuentos Previsionales = $900.000 × 0,18 = $162.000. Sueldo Imponible Neto = $738.000. Sueldo Líquido = $738.000 + $60.000 (no imponible) = $798.000.', hint: 'Calcula las cotizaciones únicamente sobre el imponible y suma íntegramente los haberes no imponibles.', points: 250 },
    { id: 411, topic: 'tributacion', type: 'multiple', question: 'Si un producto se vende a un Precio Bruto (con IVA incluido) de $119.000, ¿cuál es su Valor Neto antes de impuestos (19% IVA)?', options: ['$100.000', '$96.390', '$105.000', '$99.000'], correct: 0, explanation: 'Valor Neto = Precio Bruto / 1,19 = $119.000 / 1,19 = $100.000.', hint: 'Divide el valor total bruto entre 1,19 para aislar el neto.', points: 250 },
    { id: 412, topic: 'tributacion', type: 'multiple', question: 'Un profesional independiente emite una Boleta de Honorarios por un valor bruto de $500.000. Si la tasa de retención legal del impuesto a la renta aplicada es del 13,75%, ¿cuánto recibe en su cuenta bancaria como pago líquido?', options: ['$431.250', '$430.000', '$450.000', '$500.000'], correct: 0, explanation: 'Monto Retenido = $500.000 × 0,1375 = $68.750. Pago Líquido = $500.000 - $68.750 = $431.250.', hint: 'Resta el porcentaje de retención de impuestos al monto bruto.', points: 250 },
    { id: 413, topic: 'matematica-financiera', type: 'multiple', question: 'Inviertes $1.000.000 en un Depósito a Plazo durante 2 años con una tasa de interés compuesto anual del 10%. ¿Cuál es el monto final acumulado?', options: ['$1.210.000', '$1.200.000', '$1.100.000', '$1.220.000'], correct: 0, explanation: 'Año 1 = $1.000.000 × 1,10 = $1.100.000. Año 2 = $1.100.000 × 1,10 = $1.210.000.', hint: 'Aplica el cálculo período a período capitalizando los intereses obtenidos.', points: 250 },
    { id: 414, topic: 'analisis-financiero', type: 'multiple', question: 'Si las Ventas Totales son $50.000.000 y los Costos Fijos suman $10.000.000 con un Margen de Contribución del 40%, ¿cuál es el Punto de Equilibrio en ventas de la empresa?', options: ['$25.000.000', '$20.000.000', '$40.000.000', '$15.000.000'], correct: 0, explanation: 'Punto de Equilibrio = Costos Fijos / % Margen de Contribución = $10.000.000 / 0,40 = $25.000.000.', hint: 'Divide los costos fijos globales entre el porcentaje de margen de contribución.', points: 250 },
    { id: 415, topic: 'contabilidad', type: 'multiple', question: 'Una Pyme posee $4.000.000 en Caja y $10.000.000 en Bancos. Sus deudas corrientes son Proveedores por $3.000.000 y Préstamo Bancario Corto Plazo por $2.000.000. ¿Cuál es su Ratio de Liquidez Inmediata (Efectivo / Pasivo Corriente)?', options: ['2.8', '2.0', '1.5', '3.2'], correct: 0, explanation: 'Efectivo Total = $14.000.000. Pasivo Corriente = $5.000.000. Liquidez Inmediata = $14M / $5M = 2,8.', hint: 'Suma el efectivo y disponible inmediato y divídelo por el pasivo corriente total.', points: 250 },
    { id: 416, topic: 'nomina', type: 'multiple', question: 'Si la remuneración imponible de un trabajador es de $1.000.000, ¿cuánto debe descontar el empleador por cotización obligatoria de salud (7%) y AFP base (10%)?', options: ['$170.000', '$100.000', '$70.000', '$190.000'], correct: 0, explanation: 'Salud (7%) = $70.000. AFP Base (10%) = $100.000. Total retenido básico = $170.000.', hint: 'Suma el 10% obligatorio de pensión y el 7% legal de salud.', points: 250 },
    { id: 417, topic: 'estados-financieros', type: 'multiple', question: 'Un equipo informático costing $2.000.000 tiene una vida útil de 4 años sin valor residual. ¿Cuál es el gasto por depreciación mensual registrado en la contabilidad?', options: ['$41.667', '$50.000', '$500.000', '$166.667'], correct: 0, explanation: 'Depreciación Anual = $2.000.000 / 4 = $500.000. Depreciación Mensual = $500.000 / 12 = $41.666,67.', hint: 'Divide la depreciación de un año completo en 12 meses.', points: 250 },
    { id: 418, topic: 'tributacion', type: 'multiple', question: 'Un comercio vende mercaderías cobrando $1.190.000 precio bruto (IVA incluido) y compra suministros por $595.000 precio bruto (IVA incluido). ¿Cuál es su remanente o pago de IVA a declarar en F29?', options: ['Pago de $95.000', 'Remanente a favor de $95.000', 'Pago de $190.000', 'Pago de $57.000'], correct: 0, explanation: 'Ventas Neto = $1.000.000 → Débito IVA = $190.000. Compras Neto = $500.000 → Crédito IVA = $95.000. IVA a pagar = $190.000 - $95.000 = $95.000.', hint: 'Transforma ambos montos a valores netos dividiendo por 1,19 y luego calcula sus IVAs.', points: 250 },
    { id: 419, topic: 'analisis-financiero', type: 'multiple', question: 'Si la Utilidad Operacional (EBIT) de una empresa es $12.000.000 y los Gastos por Intereses Financieros son $3.000.000, ¿cuál es su cobertura de intereses (EBIT / Intereses)?', options: ['4,0 veces', '3,0 veces', '0,25 veces', '2,5 veces'], correct: 0, explanation: 'Cobertura = $12.000.000 / $3.000.000 = 4,0. Significa que la utilidad cubre 4 veces los intereses.', hint: 'Divide la utilidad operacional entre el total de intereses bancarios pagados.', points: 250 },
    { id: 420, topic: 'inventario', type: 'multiple', question: 'Stock Inicial = 50 unidades a $1.000 c/u. Se realiza una compra de 50 unidades a $1.200 c/u. Se venden 60 unidades usando PEPS. ¿Cuál es el valor del Inventario Final restante?', options: ['$48.000', '$40.000', '$44.000', '$50.000'], correct: 0, explanation: 'Se venden las 50u de $1.000 y 10u de $1.200. Quedan 40u del segundo lote a $1.200 = 40 × $1.200 = $48.000.', hint: 'Determina las unidades del lote más reciente que quedan en bodega.', points: 250 },
    { id: 421, topic: 'matematica-financiera', type: 'multiple', question: '¿Cuál es el valor del interés simple producido por un capital de $500.000 colocado al 5% mensual durante 4 meses?', options: ['$100.000', '$20.000', '$80.000', '$105.000'], correct: 0, explanation: 'Interés = Capital × Tasa × Tiempo = $500.000 × 0,05 × 4 = $100.000.', hint: 'Aplica la fórmula directa I = C × i × t.', points: 250 },
    { id: 422, topic: 'nomina', type: 'multiple', question: 'Un empleado con contrato a plazo fijo gana un Sueldo Imponible de $600.000. En este tipo de contrato en Chile, el Seguro de Cesantía (3%) es aportado íntegramente por el empleador. ¿Cuánto le descuentan al trabajador en su liquidación por este seguro?', options: ['$0', '$18.000', '$3.600', '$4.200'], correct: 0, explanation: 'En contratos a plazo fijo o por obra, el aporte del 3% del Seguro de Cesantía es costo 100% del empleador.', hint: 'En contratos a plazo fijo el costo previsional de cesantía corre por cuenta de la empresa.', points: 250 },
    { id: 423, topic: 'analisis-financiero', type: 'multiple', question: 'Si una empresa posee $30.000.000 en Pasivos Totales y un Patrimonio Neto de $15.000.000, ¿cuál es su Nivel de Apalancamiento Financiero (Pasivo / Patrimonio)?', options: ['2,0', '0,5', '1,5', '3,0'], correct: 0, explanation: 'Apalancamiento = $30.000.000 / $15.000.000 = 2,0. Significa que los acreedores aportan el doble de capital que los dueños.', hint: 'Divide la deuda total por los fondos propios acumulados.', points: 250 },
    { id: 424, topic: 'contabilidad', type: 'multiple', question: 'Se compra mercadería por $1.000.000 Neto pagando 50% al contado en efectivo y 50% al crédito simple con proveedores. ¿Cómo es la estructura del asiento contable?', options: ['Debe: Mercaderías $1.000.000 e IVA Crédito $190.000 / Haber: Caja $595.000 y Proveedores $595.000', 'Debe: Caja $500.000 y Proveedores $500.000 / Haber: Mercaderías $1.000.000', 'Debe: Mercaderías $1.190.000 / Haber: Caja $1.190.000', 'Debe: Ventas $1.000.000 / Haber: IVA Débito $190.000'], correct: 0, explanation: 'El costo neto va a Existencias ($1.000.000) más el IVA ($190.000). El total $1.190.000 se reparte mitad a Caja ($595.000) y mitad a Proveedores ($595.000).', hint: 'Asegúrate de que la suma de cargos en el Debe iguale los abonos en el Haber.', points: 250 },
    { id: 425, topic: 'analisis-financiero', type: 'multiple', question: 'Si la Utilidad Neta es de $6.000.000 y los Activos Totales suman $60.000.000, ¿cuál es el rendimiento sobre los activos (ROA)?', options: ['10%', '6%', '12%', '15%'], correct: 0, explanation: 'ROA = (Utilidad Neta / Activos Totales) × 100 = ($6.000.000 / $60.000.000) × 100 = 10%.', hint: 'Divide las utilidades finales entre el valor total de los activos de la empresa.', points: 250 }
];
